//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoFrota.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Veiculo
    {
		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Insira o Chassi:")]
		public string Chassi { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Insira o Tipo:")]
		public string Tipo { get; set; }

		[Display(Name = "Número de Passageiros:")]
		public int Passageiros { get; set; }

		[Required(ErrorMessage = "*Este campo é obrigatório!")]
		[Display(Name = "Insira a Cor:")]
		public string Cor { get; set; }
    }
}
